# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_03.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
# ==========================================
from .photo_viewer import PhotoViewer
from .table_part import MyTable
# ==========================================

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1632, 1035)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(80, 0))
        self.widget.setMaximumSize(QtCore.QSize(240, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(50, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.bbxModeBtn = QtWidgets.QRadioButton(self.groupBox)
        self.bbxModeBtn.setGeometry(QtCore.QRect(10, 30, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.bbxModeBtn.setFont(font)
        self.bbxModeBtn.setAcceptDrops(False)
        self.bbxModeBtn.setChecked(True)
        self.bbxModeBtn.setObjectName("bbxModeBtn")
        self.maskModeBtn = QtWidgets.QRadioButton(self.groupBox)
        self.maskModeBtn.setEnabled(False)
        self.maskModeBtn.setGeometry(QtCore.QRect(10, 60, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.maskModeBtn.setFont(font)
        self.maskModeBtn.setObjectName("maskModeBtn")
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.folderNameLabel = QtWidgets.QLabel(self.groupBox_3)
        self.folderNameLabel.setObjectName("folderNameLabel")
        self.verticalLayout_8.addWidget(self.folderNameLabel)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.imgSetRadiBtn = QtWidgets.QRadioButton(self.groupBox_3)
        self.imgSetRadiBtn.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.imgSetRadiBtn.setFont(font)
        self.imgSetRadiBtn.setObjectName("imgSetRadiBtn")
        self.horizontalLayout_6.addWidget(self.imgSetRadiBtn)
        self.videoFileBtn = QtWidgets.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.videoFileBtn.setFont(font)
        self.videoFileBtn.setChecked(True)
        self.videoFileBtn.setObjectName("videoFileBtn")
        self.horizontalLayout_6.addWidget(self.videoFileBtn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.loadFolderBtn = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.loadFolderBtn.setFont(font)
        self.loadFolderBtn.setObjectName("loadFolderBtn")
        self.verticalLayout_7.addWidget(self.loadFolderBtn)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fileLst = QtWidgets.QListView(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileLst.sizePolicy().hasHeightForWidth())
        self.fileLst.setSizePolicy(sizePolicy)
        self.fileLst.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.fileLst.setObjectName("fileLst")
        self.horizontalLayout_2.addWidget(self.fileLst)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.prevFileBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.prevFileBtn.setObjectName("prevFileBtn")
        self.horizontalLayout_4.addWidget(self.prevFileBtn)
        self.nextFileBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.nextFileBtn.setObjectName("nextFileBtn")
        self.horizontalLayout_4.addWidget(self.nextFileBtn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.labelCheckBtn_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.labelCheckBtn_2.setObjectName("labelCheckBtn_2")
        self.verticalLayout_8.addWidget(self.labelCheckBtn_2)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.edLabelToolBtn_2 = QtWidgets.QPushButton(self.widget)
        self.edLabelToolBtn_2.setObjectName("edLabelToolBtn_2")
        self.verticalLayout.addWidget(self.edLabelToolBtn_2)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        # ==============================================
        self.LabelLst = MyTable()
        # ==============================================
        self.horizontalLayout_8.addWidget(self.LabelLst)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.setAttriBtn = QtWidgets.QPushButton(self.widget)
        self.setAttriBtn.setObjectName("setAttriBtn")
        self.verticalLayout.addWidget(self.setAttriBtn)
        self.showPrevFramBtn = QtWidgets.QPushButton(self.widget)
        self.showPrevFramBtn.setObjectName("showPrevFramBtn")
        self.verticalLayout.addWidget(self.showPrevFramBtn)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.logTextEdit = QtWidgets.QTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logTextEdit.sizePolicy().hasHeightForWidth())
        self.logTextEdit.setSizePolicy(sizePolicy)
        self.logTextEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.logTextEdit.setFrameShape(QtWidgets.QFrame.Panel)
        self.logTextEdit.setObjectName("logTextEdit")
        self.verticalLayout.addWidget(self.logTextEdit)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(800, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.widget_3.setFont(font)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.folderPathLabel = QtWidgets.QLabel(self.widget_3)
        self.folderPathLabel.setObjectName("folderPathLabel")
        self.verticalLayout_6.addWidget(self.folderPathLabel)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.fileNameLabel = QtWidgets.QLabel(self.widget_3)
        self.fileNameLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.fileNameLabel.setObjectName("fileNameLabel")
        self.horizontalLayout_5.addWidget(self.fileNameLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.redoBtn = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.redoBtn.setFont(font)
        self.redoBtn.setObjectName("redoBtn")
        self.horizontalLayout_5.addWidget(self.redoBtn)
        self.undoBtn = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.undoBtn.setFont(font)
        self.undoBtn.setObjectName("undoBtn")
        self.horizontalLayout_5.addWidget(self.undoBtn)
        spacerItem2 = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.saveBtn = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saveBtn.setFont(font)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout_5.addWidget(self.saveBtn)
        self.reloadBtn = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reloadBtn.setFont(font)
        self.reloadBtn.setObjectName("reloadBtn")
        self.horizontalLayout_5.addWidget(self.reloadBtn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        # -------------------------------------------------------------
        #self.frameViewer = QtWidgets.QGraphicsView(self.widget_3)
        self.frameViewer = PhotoViewer(self.widget_3, self)
        # -------------------------------------------------------------
        self.verticalLayout_6.addWidget(self.frameViewer)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.showFramLab_2 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.showFramLab_2.setFont(font)
        self.showFramLab_2.setObjectName("showFramLab_2")
        self.horizontalLayout_11.addWidget(self.showFramLab_2)
        spacerItem3 = QtWidgets.QSpacerItem(230, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.showFramLab = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setKerning(True)
        self.showFramLab.setFont(font)
        self.showFramLab.setObjectName("showFramLab")
        self.horizontalLayout_11.addWidget(self.showFramLab)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.playerSlider = QtWidgets.QSlider(self.widget_3)
        self.playerSlider.setOrientation(QtCore.Qt.Horizontal)
        self.playerSlider.setObjectName("playerSlider")
        self.verticalLayout_6.addWidget(self.playerSlider)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ply_pausBtn = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.ply_pausBtn.setFont(font)
        self.ply_pausBtn.setObjectName("ply_pausBtn")
        self.horizontalLayout_7.addWidget(self.ply_pausBtn)
        spacerItem4 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.setStartBtn = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.setStartBtn.setFont(font)
        self.setStartBtn.setObjectName("setStartBtn")
        self.horizontalLayout_7.addWidget(self.setStartBtn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.prevFramBtn = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.prevFramBtn.setFont(font)
        self.prevFramBtn.setObjectName("prevFramBtn")
        self.horizontalLayout_7.addWidget(self.prevFramBtn)
        self.framCombo = QtWidgets.QComboBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framCombo.sizePolicy().hasHeightForWidth())
        self.framCombo.setSizePolicy(sizePolicy)
        self.framCombo.setMinimumSize(QtCore.QSize(130, 0))
        self.framCombo.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.framCombo.setFont(font)
        self.framCombo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.framCombo.setAutoFillBackground(True)
        self.framCombo.setModelColumn(0)
        self.framCombo.setObjectName("framCombo")
        self.horizontalLayout_7.addWidget(self.framCombo)
        self.nextFramBtn = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nextFramBtn.setFont(font)
        self.nextFramBtn.setObjectName("nextFramBtn")
        self.horizontalLayout_7.addWidget(self.nextFramBtn)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.setEndBtn = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.setEndBtn.setFont(font)
        self.setEndBtn.setObjectName("setEndBtn")
        self.horizontalLayout_7.addWidget(self.setEndBtn)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.frameIdLabel = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.frameIdLabel.setFont(font)
        self.frameIdLabel.setObjectName("frameIdLabel")
        self.horizontalLayout_7.addWidget(self.frameIdLabel)
        self.inFrameId = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inFrameId.sizePolicy().hasHeightForWidth())
        self.inFrameId.setSizePolicy(sizePolicy)
        self.inFrameId.setMaximumSize(QtCore.QSize(70, 16777215))
        self.inFrameId.setObjectName("inFrameId")
        self.horizontalLayout_7.addWidget(self.inFrameId)
        spacerItem8 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.showTimeInfo = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.showTimeInfo.setFont(font)
        self.showTimeInfo.setObjectName("showTimeInfo")
        self.horizontalLayout_7.addWidget(self.showTimeInfo)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout.addWidget(self.widget_3)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout.addWidget(self.frame)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 50, 171, 61))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.catCombo = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.catCombo.setAcceptDrops(True)
        self.catCombo.setAutoFillBackground(False)
        self.catCombo.setEditable(True)
        self.catCombo.setObjectName("catCombo")
        self.verticalLayout_4.addWidget(self.catCombo)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.newCatBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.newCatBtn.setFont(font)
        self.newCatBtn.setObjectName("newCatBtn")
        self.horizontalLayout_3.addWidget(self.newCatBtn)
        self.delCatBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.delCatBtn.setFont(font)
        self.delCatBtn.setObjectName("delCatBtn")
        self.horizontalLayout_3.addWidget(self.delCatBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 160, 151, 281))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.creLabelBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.creLabelBtn.setFont(font)
        self.creLabelBtn.setObjectName("creLabelBtn")
        self.verticalLayout_2.addWidget(self.creLabelBtn)
        self.removLabelBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.removLabelBtn.setFont(font)
        self.removLabelBtn.setObjectName("removLabelBtn")
        self.verticalLayout_2.addWidget(self.removLabelBtn)
        self.clrBbxBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.clrBbxBtn.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.clrBbxBtn.setFont(font)
        self.clrBbxBtn.setObjectName("clrBbxBtn")
        self.verticalLayout_2.addWidget(self.clrBbxBtn)
        self.removBbxAfterBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.removBbxAfterBtn.setFont(font)
        self.removBbxAfterBtn.setObjectName("removBbxAfterBtn")
        self.verticalLayout_2.addWidget(self.removBbxAfterBtn)
        self.clrBbxAfterBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.clrBbxAfterBtn.setObjectName("clrBbxAfterBtn")
        self.verticalLayout_2.addWidget(self.clrBbxAfterBtn)
        self.reversSeleBbxBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.reversSeleBbxBtn.setFont(font)
        self.reversSeleBbxBtn.setObjectName("reversSeleBbxBtn")
        self.verticalLayout_2.addWidget(self.reversSeleBbxBtn)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(30, 480, 131, 201))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.objAlgriCombo = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.objAlgriCombo.setObjectName("objAlgriCombo")
        self.verticalLayout_5.addWidget(self.objAlgriCombo)
        self.autoDetectBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.autoDetectBtn.setObjectName("autoDetectBtn")
        self.verticalLayout_5.addWidget(self.autoDetectBtn)
        self.trackAlgriCombo = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.trackAlgriCombo.setFont(font)
        self.trackAlgriCombo.setObjectName("trackAlgriCombo")
        self.verticalLayout_5.addWidget(self.trackAlgriCombo)
        self.startTrackBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.startTrackBtn.setFont(font)
        self.startTrackBtn.setObjectName("startTrackBtn")
        self.verticalLayout_5.addWidget(self.startTrackBtn)
        self.stopTrackBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.stopTrackBtn.setFont(font)
        self.stopTrackBtn.setObjectName("stopTrackBtn")
        self.verticalLayout_5.addWidget(self.stopTrackBtn)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(30, 880, 141, 91))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelCheckBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.labelCheckBtn.setObjectName("labelCheckBtn")
        self.verticalLayout_3.addWidget(self.labelCheckBtn)
        self.exportBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.exportBtn.setFont(font)
        self.exportBtn.setObjectName("exportBtn")
        self.verticalLayout_3.addWidget(self.exportBtn)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 850, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 450, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 690, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.edLabelToolBtn_1 = QtWidgets.QToolButton(self.groupBox_2)
        self.edLabelToolBtn_1.setGeometry(QtCore.QRect(150, 120, 31, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.edLabelToolBtn_1.setFont(font)
        self.edLabelToolBtn_1.setObjectName("edLabelToolBtn_1")
        self.setLabelRangeBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.setLabelRangeBtn.setGeometry(QtCore.QRect(30, 800, 141, 31))
        self.setLabelRangeBtn.setObjectName("setLabelRangeBtn")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 720, 160, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.showStartLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.showStartLabel.setFont(font)
        self.showStartLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.showStartLabel.setObjectName("showStartLabel")
        self.horizontalLayout_9.addWidget(self.showStartLabel)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 760, 161, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.showEndLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.showEndLabel.setFont(font)
        self.showEndLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.showEndLabel.setObjectName("showEndLabel")
        self.horizontalLayout_10.addWidget(self.showEndLabel)
        self.horizontalLayout.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1632, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(False)
        self.statusbar.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.statusbar.setAcceptDrops(False)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Mode"))
        self.bbxModeBtn.setText(_translate("MainWindow", "Bounding box"))
        self.maskModeBtn.setText(_translate("MainWindow", "Mask Polygon"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Load File"))
        self.folderNameLabel.setText(_translate("MainWindow", "folder_Name"))
        self.imgSetRadiBtn.setText(_translate("MainWindow", "image set"))
        self.videoFileBtn.setText(_translate("MainWindow", "video file"))
        self.loadFolderBtn.setText(_translate("MainWindow", "Load Folder"))
        self.prevFileBtn.setText(_translate("MainWindow", "<"))
        self.nextFileBtn.setText(_translate("MainWindow", ">"))
        self.labelCheckBtn_2.setText(_translate("MainWindow", "Label Checker"))
        self.edLabelToolBtn_2.setText(_translate("MainWindow", "Object Manager"))
        self.label_6.setText(_translate("MainWindow", "Labels"))
        self.setAttriBtn.setText(_translate("MainWindow", "Set Attribute After Time"))
        self.showPrevFramBtn.setText(_translate("MainWindow", "Show Prev. Frame"))
        self.label_9.setText(_translate("MainWindow", "Labeling logs"))
        self.folderPathLabel.setText(_translate("MainWindow", "folder_Path"))
        self.fileNameLabel.setText(_translate("MainWindow", "file_Name"))
        self.redoBtn.setText(_translate("MainWindow", "Redo"))
        self.undoBtn.setText(_translate("MainWindow", "Undo"))
        self.saveBtn.setText(_translate("MainWindow", "Save"))
        self.reloadBtn.setText(_translate("MainWindow", "Reload"))
        self.showFramLab_2.setText(_translate("MainWindow", "showFrameLabel"))
        self.showFramLab.setText(_translate("MainWindow", "showFrameLabel"))
        self.ply_pausBtn.setText(_translate("MainWindow", "Play"))
        self.setStartBtn.setText(_translate("MainWindow", "Set Start"))
        self.prevFramBtn.setText(_translate("MainWindow", "<"))
        self.nextFramBtn.setText(_translate("MainWindow", ">"))
        self.setEndBtn.setText(_translate("MainWindow", "Set End"))
        self.frameIdLabel.setText(_translate("MainWindow", "Go to Frame index:"))
        self.showTimeInfo.setText(_translate("MainWindow", "time_display"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Label Editor"))
        self.newCatBtn.setText(_translate("MainWindow", "New"))
        self.delCatBtn.setText(_translate("MainWindow", "Delete"))
        self.creLabelBtn.setText(_translate("MainWindow", "Create"))
        self.removLabelBtn.setText(_translate("MainWindow", "Remove"))
        self.clrBbxBtn.setText(_translate("MainWindow", "Clear All"))
        self.removBbxAfterBtn.setText(_translate("MainWindow", "Remove After Time"))
        self.clrBbxAfterBtn.setText(_translate("MainWindow", "Clean All After Time"))
        self.reversSeleBbxBtn.setText(_translate("MainWindow", "Reverse Select"))
        self.autoDetectBtn.setText(_translate("MainWindow", "Auto Detect"))
        self.startTrackBtn.setText(_translate("MainWindow", "Start Track"))
        self.stopTrackBtn.setText(_translate("MainWindow", "Stop Track"))
        self.label_2.setText(_translate("MainWindow", "Bounding box"))
        self.label_3.setText(_translate("MainWindow", "Category"))
        self.labelCheckBtn.setText(_translate("MainWindow", "Label Checker"))
        self.exportBtn.setText(_translate("MainWindow", "Export"))
        self.label_4.setText(_translate("MainWindow", "Labeling Data "))
        self.label_5.setText(_translate("MainWindow", "Labeling Assist"))
        self.label_7.setText(_translate("MainWindow", "Event Interval"))
        self.edLabelToolBtn_1.setText(_translate("MainWindow", "..."))
        self.setLabelRangeBtn.setText(_translate("MainWindow", "Set Label in Range"))
        self.label.setText(_translate("MainWindow", "Start:"))
        self.showStartLabel.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "End:"))
        self.showEndLabel.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

